"use client";

import { useEffect, useRef, useState } from "react";

const LESSONS=[
  {word:'hello',phrase:'Hello, how are you?',tip:'Start with a warm greeting.'},
  {word:'please',phrase:'Could you help me, please?',tip:'Use please to make a polite request.'},
  {word:'confident',phrase:'I feel confident speaking today.',tip:'Say each syllable slowly, then naturally.'},
  {word:'perspective',phrase:'Could you tell me your perspective?',tip:'Practice the longer word in small parts.'},
  {word:'conversation',phrase:'I can start a conversation.',tip:'Keep a steady pace and clear ending.'},
];

export default function VoiceJourneyPage(){
 const [i,setI]=useState(0),[saved,setSaved]=useState<string[]>([]),[msg,setMsg]=useState(''); const [recording,setRecording]=useState(false); const [audioUrl,setAudioUrl]=useState(''); const media=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]); const lesson=LESSONS[i];
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem('eccoozs-voice-saved')||'[]'))}catch{}},[]);
 function speak(text:string){if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.82;speechSynthesis.speak(u)}}
 function saveWord(){const next=[...new Set([...saved,lesson.word])];setSaved(next);localStorage.setItem('eccoozs-voice-saved',JSON.stringify(next));setMsg('Added to My Words ✓');setTimeout(()=>setMsg(''),1200)}
 async function toggleRecord(){if(recording){media.current?.stop();return;} try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}); const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType});setAudioUrl(URL.createObjectURL(blob));setRecording(false);stream.getTracks().forEach(t=>t.stop())};media.current=r;r.start();setRecording(true);}catch{setMsg('Microphone access was not available.');}}
 return <main className="vj"><style>{`
 *{box-sizing:border-box}.vj{min-height:100vh;background:linear-gradient(135deg,#fbfaff,#f2edff);font-family:Arial,sans-serif;color:#111a4a;padding:28px}.wrap{max-width:980px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:24px;font-weight:900;color:#5730c9;text-decoration:none}.saved{background:#fff;border:1px solid #ddd2ff;border-radius:999px;padding:10px 14px;font-weight:800}.card{margin-top:26px;background:#fff;border:1px solid #e3dcff;border-radius:26px;overflow:hidden;box-shadow:0 20px 55px #5830c91a}.hero{padding:28px;background:linear-gradient(135deg,#5f35d5,#7e54e7);color:#fff}.hero h1{font-size:38px;margin:0 0 8px}.hero p{margin:0;opacity:.82;line-height:1.6}.body{display:grid;grid-template-columns:.85fr 1.15fr;gap:20px;padding:24px}.lessonlist{display:grid;gap:9px}.lessonbtn{padding:13px;text-align:left;border:1px solid #e5deff;background:#faf8ff;border-radius:12px;font-weight:800;cursor:pointer}.lessonbtn.on{background:#6036d4;color:#fff}.practice{background:#faf8ff;border:1px solid #e5deff;border-radius:20px;padding:24px;text-align:center}.label{font-size:12px;text-transform:uppercase;letter-spacing:.16em;color:#7353d5;font-weight:900}.word{font-family:Georgia,serif;font-size:44px;margin:12px 0}.phrase{font-size:22px;line-height:1.5;margin:8px auto 18px;max-width:540px}.tip{color:#6d68a1;line-height:1.6}.buttons{display:flex;gap:9px;justify-content:center;flex-wrap:wrap;margin-top:18px}.btn{border:0;border-radius:10px;padding:11px 14px;font-weight:800;cursor:pointer}.primary{background:#6036d4;color:#fff}.light{background:#ebe4ff;color:#3b257e}.record{background:#fff;border:1px solid #dcd2ff;color:#3b257e}.record.on{background:#ffe7ee;color:#a31440}.msg{height:22px;margin-top:10px;font-weight:800;color:#6036d4}.player{margin-top:12px}.footer{text-align:center;margin-top:18px}.footer a{color:#6036d4;font-weight:800;text-decoration:none}@media(max-width:720px){.body{grid-template-columns:1fr}.vj{padding:14px}.hero h1{font-size:31px}.word{font-size:38px}}
 `}</style><div className="wrap"><div className="top"><a className="brand" href="/welcome">✦ My Voice Journey</a><div className="saved">My Words · {saved.length}</div></div><section className="card"><div className="hero"><h1>Learning to Speak</h1><p>Practice words step by step until you can share a whole conversation.</p></div><div className="body"><div className="lessonlist">{LESSONS.map((x,n)=><button key={x.word} className={`lessonbtn ${n===i?'on':''}`} onClick={()=>{setI(n);setMsg('');setAudioUrl('')}}>{n+1}. {x.word}</button>)}</div><div className="practice"><div className="label">Word in Focus</div><div className="word">{lesson.word}</div><button className="btn light" onClick={()=>speak(lesson.word)}>🔊 Hear word</button><div className="phrase">{lesson.phrase}</div><button className="btn light" onClick={()=>speak(lesson.phrase)}>🔊 Hear phrase</button><p className="tip">{lesson.tip}</p><div className="buttons"><button className="btn primary" onClick={saveWord}>＋ Add to My Words</button><button className={`btn record ${recording?'on':''}`} onClick={toggleRecord}>{recording?'■ Stop recording':'🎙 Record myself'}</button><button className="btn light" onClick={()=>setI(v=>(v+1)%LESSONS.length)}>Next →</button></div>{audioUrl&&<div className="player"><audio controls src={audioUrl}/></div>}<div className="msg">{msg}</div></div></div></section><div className="footer"><a href="/learning">← All ECCOOZS Learning Apps</a></div></div></main>
}
